version: '1.0'

services:
  db:
    image: postgres:14.12
    container_name: nice_zhukovsky
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5433:5432" # 將宿主機的5433端口映射到容器的5432端口
  app:
    image: spring.app:1.0
    container_name: springproject
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
    depends_on:
      - db
    ports:
      - "8080:8080"
