spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workpractice_event?useSSL=false&serverTimezone=UTC
    username: postgres
    password: B3sTpa55w0rd
    driver-class-name: org.postgresql.Driver