spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: html
    encoding: UTF-8

# mybatis 整合 mybatis 可以拋棄 mybatis-config.xml
mybatis:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
    mapper-locations: classpath:mappers/*.xml
    config-location: classpath:mybatis-config.xml